### ISSUE TITLE
Weave expose fails randomly on node reboot

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1249]
Weave bridge creation is sometimes really slow and this causes expose to fail. 

Related: https://github.com/weaveworks/weave/issues/2479

**Comment by SpComb** [comment]
Reference for #1178 for the missing `weaveexec` error handling that makes debugging this more difficult.

The `weaver` router runs as a [`--restart=always`](https://github.com/weaveworks/weave/blob/v1.7.2/weave#L331) Docker container, and it will automatically be started by Docker at boot. However, the `weave` container itself will not create the weave bridges:

```
core@coreos-dev-02 ~ $ sudo reboot`
Connection to 127.0.0.1 closed by remote host.
$ vagrant ssh coreos-dev-02
Last login: Fri Oct 28 11:14:45 UTC 2016 from 10.0.2.2 on pts/1
CoreOS alpha (1192.2.0)
Update Strategy: No Reboots
core@coreos-dev-02 ~ $ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                                  PORTS               NAMES
33f1ab2f5ca9        weaveworks/weave:1.7.2   "/home/weave/weaver -"   31 minutes ago      Up Less than a second                                       weave
e3034629a322        kontena/etcd:2.3.3       "/usr/bin/etcd --name"   6 weeks ago         Restarting (1) Less than a second ago                       kontena-etcd
core@coreos-dev-02 ~ $ docker logs weave
INFO: 2016/10/28 11:45:27.372827 === received SIGINT/SIGTERM ===
*** exiting
INFO: 2016/10/28 11:45:57.881509 Command line options: map[dns-listen-address:172.18.0.1:53 http-addr:127.0.0.1:6784 datapath:datapath dns-domain:kontena.local log-level:debug name:ba:7a:6c:b1:e8:55 nickname:coreos-dev-02 port:6783 resolv-conf:/var/run/weave/etc/resolv.conf dns-effective-listen-address:172.18.0.1 ipalloc-range:]
```

After the initial ["Command line options: ..." logging](https://github.com/weaveworks/weave/blob/v1.7.2/prog/weaver/main.go#L207), it will stop and wait for the `-datapath=datapath` interface to appear ([`createOverlay()`](https://github.com/weaveworks/weave/blob/v1.7.2/prog/weaver/main.go#L224) -> [`EnsureInterface()`](https://github.com/weaveworks/weave/blob/v1.7.2/prog/weaver/main.go#L403). This spins waiting for the [interface to appear in netlink](`https://github.com/weaveworks/weave/blob/v1.7.2/net/if.go#L20`)].

Meanwhile, the initial `weaveexec launch-router` command issued by the kontena-agent at start will error out instead of creating the bridge, since the weaver router is already running, waiting for the bridge to be created...

`docker run --rm --network host --privileged -v /var/run/docker.sock:/var/run/docker.sock weaveworks/weaveexec:1.7.2 launch-router --ipalloc-range= --dns-domain kontena.local 172.17.8.101`
```
weave is already running; you can stop it with 'weave stop-router'.
```

It seems like the way this is supposed to work at boot is for the weave proxy to [call `weaveexec attach-router`](https://github.com/weaveworks/weave/blob/v1.7.2/proxy/proxy.go#L495), which indeed creates the bridge and allows `weaver` to continue:

`docker run --rm --network host --privileged -v /var/run/docker.sock:/var/run/docker.sock weaveworks/weaveexec:1.7.2 attach-router`
`ip link show datapath`
```
6: datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether ba:c5:2a:2f:00:d2 brd ff:ff:ff:ff:ff:ff
```
`ip link show weave   `
```
8: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ba:7a:6c:b1:e8:55 brd ff:ff:ff:ff:ff:ff
```
`docker logs weave`
```
INFO: 2016/10/28 11:45:57.881509 Command line options: map[dns-listen-address:172.18.0.1:53 http-addr:127.0.0.1:6784 datapath:datapath dns-domain:kontena.local log-level:debug name:ba:7a:6c:b1:e8:55 nickname:coreos-dev-02 port:6783 resolv-conf:/var/run/weave/etc/resolv.conf dns-effective-listen-address:172.18.0.1 ipalloc-range:]
INFO: 2016/10/28 11:50:39.320973 Communication between peers is unencrypted.
INFO: 2016/10/28 11:50:39.334429 Our name is ba:7a:6c:b1:e8:55(coreos-dev-02)
INFO: 2016/10/28 11:50:39.335754 Restart/resume detected - using persisted peer list: [172.17.8.101]
INFO: 2016/10/28 11:50:39.346752 Docker API on unix:///var/run/docker.sock: &[Version=1.12.1 ApiVersion=1.24 GitCommit=7a86f89 GoVersion=go1.6.3 Os=linux Arch=amd64 KernelVersion=4.7.3-coreos-r1]
INFO: 2016/10/28 11:50:39.347629 Listening for DNS queries on 172.18.0.1
INFO: 2016/10/28 11:50:39.347648 Sniffing traffic on datapath (via ODP)
INFO: 2016/10/28 11:50:39.393123 ->[172.17.8.101:6783] attempting connection
INFO: 2016/10/28 11:50:39.401879 Listening for HTTP control messages on 127.0.0.1:6784
...
```

It's a bit of a myster to me how weave currently ever does start at boot, since the kontena-agent does not run the weave proxy or the `weavexec attach-router` command.

I suggest using `weaveexec launch-router --no-restart` to start weave, meaning that it will not automatically get started at boot, and the same kontena-agent weave start process will happen at each boot, including reboots.

**Comment by SpComb** [comment]
This behavior of the initial `weaveexec launch-router` failing after a reboot seems like something that changed from 1.5.2 to 1.7.2:

[Weave 1.5.2 `launch-router`](https://github.com/weaveworks/weave/blob/v1.5.2/weave#L2034):

```
    launch-router)
        deprecation_warnings "$@"
        launch_router "$@"
;;
```

[Weave 1.7.2 `launch-router`](https://github.com/weaveworks/weave/blob/v1.7.2/weave#L1977):

```
    launch-router)
        deprecation_warnings "$@"
        check_not_running router $CONTAINER_NAME $BASE_IMAGE
        launch_router "$@"
        echo $ROUTER_CONTAINER
;;
```

Note the addition of the `check_not_running` case that causes the previous kontena-agent behavior to fail... AFAIK the Weave 1.5.2 implementation would work in the same situation (`weaveexec launch-router` after reboot with an autostarting Docker weave container)
