### ISSUE TITLE
VPN mesh

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#1452]
If I understand correctly kontena use VPN at host level to connect the nodes, and it uses OpenVPN for the task.

is ther any plan to use some mesh vpn? (tinc/peervpn)

I got better velocity results using this type of VPN and as side effect they are lighter in the host.

Thanks

**Comment by jnummelin** [comment]
On node level, Kontena uses network technology called [Weave](https://www.weave.works/products/weave-net/) to create the overlay network between all the nodes in the grid. By default Weave operates on a mesh-type architecture and thus you can create pretty complex deployments.

**Comment by jalberto** [comment]
but weave dont do the VPN part right? I mean the encryption.

In other hand, how kontena will behave in a topology like mine?:

- 2 providers (azure, scealway)
- 1 bastion/fw in each provider doing NAT
- N nodes conly with private IP in each provider

Thanks!

**Comment by jnummelin** [comment]
Weave does do encryption but it's not VPN protocol.

Are the bastion hosts part of the grid?

To make you scenario work like a charm you have to do couple of things.

First put proper labels for nodes in each provider. Use `region=azure` and `region=scaleway` for example. The `region` label is something that Kontena recognizes and is then able to figure out the "location" of the nodes. It will then configure weave so that it peers within the same region using private networking.

Second part is to configure trusted subnets. A trusted subnet is a defined (private) subnet in which the traffic is not encrypted. When weave does not need to encrypt the traffic is operates with much less overhead. Let's take and example:
On Azure you have private subnet for the nodes: `192.168.0.0/16` and on Scaleway `172.20.20.0/24`. Then configure both subnets as trusted:
```
kontena grid trusted-subnet add <grid> 192.168.0.0/16
kontena grid trusted-subnet add <grid> 172.20.20.0/24
```

If the bastion hosts are not part of the grid itself the setup requires some "manual" steps. Run weave on the bastion hosts and configure them so that they have peer connections to all of the nodes in the private network AND to the other providers bastion. When you do this on both "sides" magic will happen. All of your containers can talk to each other regardless where they are running. As Weave is a mesh-type of solution this works nicely in your situation as it can do multi-hop routing and the public link between bastion hosts is then automatically encrypted by weave. Naturally this means that there will be overhead between the public link as the encryption is done. Plus of course the link itself may not be that fast.

We've tried these kind of solutions and as long as your apps can tolerate the network conditions it really works like magic. :)

**Comment by jalberto** [comment]
That sounds really nice, will try. Thanks!
