### ISSUE TITLE
Cadvisor / Weave confuses Docker in CoreOS Beta

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#1567]
See: https://github.com/weaveworks/weave/issues/2559#issuecomment-267553417

**Comment by jnummelin** [comment]
I _think_ it is because of the `nsenter` trick our image does as it doesn't happen with the official `google/cadvisor` cadvisor image. (same version of cadvisor itself).

Also looking at:
```
core@jussi-weave-test ~ $ docker run -d -v /:/host:rw --net host --pid host --privileged --name cadvisor kontena/cadvisor:0.23.2 --docker_only --listen_ip=127.0.0.1 --port=8989 --storage_duration=2m --housekeeping_interval=30s
bd801016c4bc0316f7782e71b716547fbf3b3c48ad9acb271bb693c0b607e431
core@jussi-weave-test ~ $ docker exec -ti cadvisor sh
sh-4.3# ls -lah /host                                                                                                                                                                                   
ls: cannot access '/host': No such file or directory
```
Makes me think the `nsenter` is somehow really messing up things in the container mounts.

Making Kontena use the "official" cAdvisor image could be one solution for this. cAdvisor 0.23.3 seems to have fixed the issue with `du -sh` hogging all CPU in https://github.com/google/cadvisor/releases/tag/v0.23.3

**Comment by jakolehm** [comment]
Official cAdvisor image sounds good to me (if it does not consume too much resources).

**Comment by jnummelin** [comment]
Yes, I'll test the setup with the problematic Ubuntu+aufs combo with plenty of containers to see if it still breaks or not.

**Comment by jnummelin** [comment]
Running Ubuntu/aufs with 100+ containers yields cadvisor with few percent CPU usage and ~23M mem usage with the official image. IMO not too bad.
![image](https://cloud.githubusercontent.com/assets/3205505/21304026/247d3dc0-c5cb-11e6-8fa7-5032bbc936c1.png)
