### ISSUE TITLE
Stack upgrade --deploy return code should not be zero

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/kontena#1637]
When the command `kontena stack upgrade --deploy stack` has one or more errors, the return code should be non-zero. It's currently zero.

```
* Deploying stack stack. 
        halting deploy of grid/stack/service, one or more instances failed
```

The return code can be utilized in a build server to fail the build if the stack upgrade & deploy command fails.

Relevant code:
https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/stacks/upgrade_command.rb#L24

Also, I would be interested to know if that error message means that every other service in the stack deployed successfully.

**Comment by SpComb** [comment]
The bug here is that the top-level `bin/kontena` script and the internal `Kontena.run(...)` functions behave differently in error conditions, which in this case means that `kontena stack deploy || echo fail` behaves correctly and exits with a non-zero status, but `kontena stack upgrade --deploy ...` ignores the internal `Kontena.run(...)` error condition, and exits with the incorrect zero status.

The `Kontena::Command#run` expects `Kontena::Command#execute` to either return `false` or raise an Exception. The `Kontena::Cli::Stacks::DeployCommand` does not return false, it will raise an error. The top-level `bin/kontena` script will rescue exceptions and abort, exiting with a non-zero exit code. This means that that `kontena stack deploy ...` itself will correctly exit with a non-zero status.

The `Kontena.run(...)` function will also rescue the exception, returning a non-zero exit status Integer. When this is a `Kontena::Command#execute` tail-call, this returned Integer exit status will be ignored by `Kontena::Command#run`, meaning that the top-level command exits with a zero status.

The `Kontena.run` function should either be fixed to return false, or `Kontena::Command#run` fixed to interpret a non-zero integer return value. This will work if the `Kontena.run` is used as a tail-call, or the return value is explicitly checked... it might be more robust for `Kontena.run` to just raise the exception, or replace the internal use of `Kontena.run` with direct method calls instead.

**Comment by kke** [comment]
@SpComb I suspect 1.2 fixed this.
