### ISSUE TITLE
Deploying stack with daemon strategy and scale=0

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1671]
I'm migrating my galera cluster to stacks and I wanted to launch the stack initially with the "node" service scaled to 0 although the .yml file specifies 1. I was going to then bootstrap it with the "seed" service and finally return the "node" service back to "scaling: 1". Steps:

    $ kontena stack install kontena-galera-cluster.yml
    $ kontena stack build -f kontena-galera-cluster.yml
    $ kontena service scale galera-cluster/node 0
    $ kontena service show galera-cluster/node
    # showed scaling: 0
    $ kontena stack deploy galera-cluster

Expected result: the "node" service would be deployed to 0 nodes.
Actual result: the "node" service was deployed to each node as if "scaling: 1".

After it completed deploying I noticed that "scaling:" had been reverted to 1. So is this simply because deploying a stack overrides the services?

I'm looking for a way to scale down a service that is part of a stack before the stack is deployed, or perhaps deploy only a subset of services from a stack.

Thanks!

**Comment by SpComb** [comment]
> After it completed deploying I noticed that "scaling:" had been reverted to 1. So is this simply because deploying a stack overrides the services?

Yes, deploying a stack will override any scaling/instances parameters on the existing services.

> I'm looking for a way to scale down a service that is part of a stack before the stack is deployed, or perhaps deploy only a subset of services from a stack.

If you do a `kontena stack install` without deploying it, then you should be able to see those stack's services in `kontena service ls`. Try doing a `kontena service deploy stack/foo` for the individual services that you want deployed, beforeusing `kontena stack deploy` to deploy the rest? That won't work for a `kontena stack upgrade`, though, since it will only create new services, not update existing ones.

**Comment by colinmollenhour** [comment]
Ah, thanks. I don't know why it didn't occur to me to try deploying the service without deploying the full stack, I guess I just don't fully understand the relationship. I was looking for a command similar to `kontena stack deploy mystack someservice` that would deploy only part of the stack, but I believe you're saying that `kontena service deploy mystack/someservice` is already the exact equivalent of that?
