### ISSUE TITLE
Stack deploy should respect service running status

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/kontena#1767]
Current behavior:
1. Every service of stack-a is running
2. Stop stack-a/service-a
3. Deploy stack-a
4. service-a is running

Expected behavior:
1. Every service of stack-a is running
2. Stop stack-a/service-a
3. Deploy stack-a
4. Every service other than service-a is running

The use case here is to do update deployments in a controlled way. We want to e.g. shut down the web server, then update every service and verify everything works 💯%, then after that start the (updated) web server.

**Comment by SpComb** [comment]
IMO it's good that `kontena stack deploy` will start any stopped services, it ensures that the stack will be working/running after a deploy, even if you forgot that you had some services stopped.

I think the ideal workaround for these kind of "manual" stack deployments would be to use `kontena stack upgrade --no-deploy` followed by a manual `kontena service deploy` of any services that you would like to have running.

Unfortunately, this workaround doesn't work, because `kontena stack upgrade --no-deploy` will not actually update the services. Only `kontena stack deploy` will apply the changes from the stack revision  to the actual grid services on the master, allowing you to deploy the services, but that command/API will also deploy all the services. Filed #2311 to propose changing this.

Closing this issue in favor of the #2311 design proposal to allow the `kontena stack upgrade --no-deploy` + manual `kontena service deploy` workaround.
