### ISSUE TITLE
Stack deploy should stop if image pulling fails

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1829]
```
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
Kontena::Workers::ImagePullWorker: image pull failed: No such image: lollol:8.7
```

Not sure if 1.2 fixes this also?

**Comment by matti** [comment]
was actually `write /var/lib/docker/tmp/GetImageBlob996801118: no space left on device`

**Comment by SpComb** [comment]
The `kontena stack deploy` errors should improve with #1607 + some additional server scheduler changes to propagate the errors to the CLI.

OTOH I would expect the agent to log any Docker API `/images/create` errors instead of just "No such image"... was the `write ...: no space left on device` error only found in the `docker.service` logs?

**Comment by SpComb** [comment]
Service container create errors from the agent should now propagate back to the server in Kontena 1.2, and error out the service deploy as well as the stack deploy.
