### ISSUE TITLE
Adding second node kiing the weave network : ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1:

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2185]
I am new to Kontena. Trying to setup Kontena for production in private in-house cloud. But facing setup problem. Need urgent help
OS Details
----------------------
Ubuntu 16.10
Docker
----------------------------
Client:
 Version:      1.12.6
Server:
 Version:      1.12.6
 API version:  1.24

Docker-compose 
------------------------------------
docker-compose version 1.11.2, build dfed245

Image
-----MASTER---------
kontena/haproxy:latest  
kontena/server:latest 
mongo:3.0

------AGENT---
kontena/etcd:2.3.7  
kontena/ipam-plugin:0.2.2 
weaveworks/weave:1.8.2 
kontena/agent:latest
 google/cadvisor:v0.24.1

Steps followed
--------------

1. We are using Private cloud. Using Vmware VSpere client created nodes. 1-master, 2-nodes
2. Master looks running fine.
3. When I add first agent, Its showing in "Kontena node list" as well as in "Kontena-io"
4. When I add second agent, this agent never showing in the node list or Kontena-io"
4. Also when I execute "Kontena etcd health". its always showing unhealthy. It looks When I add second node its killing the "etdc".  

**At first getting below error.**

kontena-agent | E, [2017-04-20T05:27:32.505696 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "<redacted>", "--trusted-subnets", ""]
kontena-agent | weave is already running; you can stop it with 'weave stop-router'.

**second showing below error** 
AUS-CBR-D2-1 | Kontena::NetworkAdapters::IpamError: 500 "Internal Server Error"
AUS-CBR-D2-1 |  /app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
AUS-CBR-D2-1 |  /app/lib/kontena/network_adapters/ipam_client.rb:47:in `rescue in reserve_pool'
AUS-CBR-D2-1 |  /app/lib/kontena/network_adapters/ipam_client.rb:34:in `reserve_pool'
AUS-CBR-D2-1 |  /app/lib/kontena/network_adapters/weave.rb:211:in `ensure_default_pool'
AUS-CBR-D2-1 |  /app/lib/kontena/network_adapters/weave.rb:181:in `on_ipam_start'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
AUS-CBR-D2-1 |  /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
AUS-CBR-D2-1 | I, [2017-04-19T02:32:20.203828 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized

**at last I see all the way only below error.**

AUS-CBR-D2-1 | E, [2017-04-19T02:35:43.213908 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena
AUS-CBR-D2-1 | E, [2017-04-19T02:39:13.263598 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena
AUS-CBR-D2-1 | E, [2017-04-19T02:42:43.301408 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena
AUS-CBR-D2-1 | E, [2017-04-19T02:46:13.340524 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena
AUS-CBR-D2-1 | E, [2017-04-19T02:49:43.383594 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena

**Comment by SpComb** [comment]
> ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ... weave is already running; you can stop it with 'weave stop-router'.

This is a known issue (#1397), and the error itself is harmless.

> `Kontena::NetworkAdapters::IpamError: 500 "Internal Server Error"`

There should be a better error in the `kontena-ipam-plugin` container's logs, presumably some `Etcd::Error` variant. TODO on improving these error messages to reveal the underlying problem: https://github.com/kontena/kontena-ipam/issues/59

The `kontena-etcd` container logs should then in turn contain the root error... presumably something related to the networking configuration on the nodes.

It seems that your `kontena-etcd` is still running, though, because it's failing with `AddressPool not found: kontena` instead of some internal error?

> * When I add first agent, Its showing in "Kontena node list" as well as in "Kontena-io"
> * When I add second agent, this agent never showing in the node list or Kontena-io"
> * Also when I execute "Kontena etcd health". its always showing unhealthy. It looks When I add second node its killing the "etdc".

Unforunately there's not enough logs here in this issue to tell what's going on exactly. The `weave` and `kontena-etcd` container logs could reveal more details. However, not having the second agent show up in `kontena node list` while still causing the first node to break would lead me to guess that the two host nodes are sharing the same Docker ID, causing Kontena to consider both agents as being the same host node.

Did you create the two VMWare host nodes by cloning an image after installing Docker? Does `docker info` on the two nodes show an identical `ID: XI4K:NPO...4A:63S5` field? Every host node must have an unique Docker ID.

**Comment by santhoshkumarhirekerur** [comment]
This all errors where throwing because of same Docker ID in all nodes. Once its fixed now all nodes running without any error. Thanks for the great support. Yes you are right. Its because of creating and using same image template in creating VM.
