### ISSUE TITLE
How to change Weave defalut host. Its confilicting with other IP

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2186]
The Weave default using 10.81.. ..   We already using this IP series to connect  Japan hosts.  So I need to change this IP as our convenience. How to do it?  like something to 10.61.. series.

Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.1/16
 Exposed host node at cidr=10.81.0.1/16

**Comment by SpComb** [comment]
The new Kontena 1.2 release will include support for something like [`kontena grid create --supernet=10.61.0.0/16 --subnet=10.61.0.0/18`](https://github.com/kontena/kontena/blob/v1.2/docs/using-kontena/grids.md#grid-subnet-supernet) exactly for this kind of case.

The 1.2.0 release should be out soon, in the meantime you can already start using the release candidates for testing, and then upgrade to the final release once it comes out.

Note that we don't support changing the grid subnet after the fact, so you will need to re-create any grid in order to move away from the default `10.80.0.0/12` address space.

**Comment by jnummelin** [comment]
Closing this as 1.2.0 was released last week.
