### ISSUE TITLE
Random strategy moves services constantly

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2244]
Regression in 1.2.x

**Comment by SpComb** [comment]
This issue is caused by the refactoring in Kontena 1.2 to merge the separate [`ServiceBalancerJob`](https://github.com/kontena/kontena/blob/v1.1/server/app/jobs/service_balancer_job.rb) and [`GridSchedulerWorker`](https://github.com/kontena/kontena/blob/v1.1/server/app/jobs/grid_scheduler_worker.rb) into a single [`GridSchedulerJob`](https://github.com/kontena/kontena/blob/v1.2/server/app/jobs/grid_scheduler_job.rb) in #1873. Instead of only invoking the `GridScheduler` rescheduling logic to re-evaluate the scheduler strategy in specific circumstances, it is now run continuously, replacing the separate `ServiceBalancerJob` checks.

Services using the `random` strategy would still get shuffled around across nodes on each service deploy with Kontena 1.1, but these service deploys would not be triggered by the continuously running [ServiceBalancerJob](https://github.com/kontena/kontena/blob/v1.1/server/app/jobs/service_balancer_job.rb), as it only compared the number of running service containers, without re-evaluating the scheduler strategy. Certain events would still invoke the the [`GridScheduler`](https://github.com/kontena/kontena/blob/v1.1/server/app/services/grid_scheduler.rb) rescheduling logic, causing services using the `random` strategy to get re-deployed in a similar fashion:

* nodes connecting: [`Agent::NodePlugger`](https://github.com/kontena/kontena/blob/v1.1/server/app/services/agent/node_plugger.rb#L35)
* nodes being removed: [`HostNodes::Remove`](https://github.com/kontena/kontena/blob/v1.1/server/app/mutations/host_nodes/remove.rb#L17)
* on `kontena grid update`, as part of the #1564 `--default-affinity` feature: [Grids::Update](https://github.com/kontena/kontena/blob/v1.1/server/app/mutations/grids/update.rb#L71))

With Kontena 1.2, these spurious re-deployments of services using the `random` strategy now happen continuously, as the continuous [`GridSchedulerJob`](https://github.com/kontena/kontena/blob/v1.2/server/app/jobs/grid_scheduler_job.rb) now runs the `GridScheduler` logic, which re-evaluates the service scheduler strategy each time. Running the [`GridScheduler`](https://github.com/kontena/kontena/blob/v1.2/server/app/services/grid_scheduler.rb) rescheduling logic continuously assumes that the scheduler strategy is deterministic, and only returns a different set of nodes when new nodes are connected, nodes are removed, or the default affinity filters are changed. This is true for the default `ha` strategy and the derived `daemon` strategy. However the `random` strategy will return different nodes each time it is called, resulting in the `random` service being shuffled around across nodes constantly. This is more likely to happen the fewer instances of the service there are compared to available host nodes.
