### ISSUE TITLE
How to Handle the volume when we scale the service?

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2283]
We are working on setting up kontena for production.  I have few questions still are not clear to me. I will be glad if I get answers.
Question 1: 
1. We have private in-house cloud and I have configured kontena.yml as below and running in single node.  Its running fine.

stack: docker/traefik
version: 0.3.0
services:
  internet_lb:
    image: kontena/lb:latest
    ports:
      - 180:80
  traefik:
    image: traefik
    environment:
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_VIRTUAL_HOSTS=kontena.test.com
    links:
      - internet_lb
    stateful: true
    command: --configFile=/var/traefik/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/traefik-master/traefik.toml:/var/traefik/traefik.toml
      - /root/traefik-master/acme:/acme

2. Now I am trying scale this app with below command
kontena service scale traefik/traefik 2

Now I can see two instances of it. My question is Do I need to sync volumes between different host " /root/traefik-master/traefik.toml" manually or Is Kontena will take care of this internally?

Question 2: How to take the backup of master?   If master crash how quick we can bring this up from backup?
Question 3: Is master used for only deploy services?  what is the role of master with existing/running services in grid?

**Comment by jnummelin** [comment]
> Do I need to sync volumes between different host " /root/traefik-master/traefik.toml" manually or Is Kontena will take care of this internally?

This type of volumes mount something from the host to the container. As such there are no real volumes in play here. Now when you mount files from host to the container, there's nothing automatically syncing up the host side files between nodes. Not unless you put something in place for that yourself.

> How to take the backup of master? 

You can backup the mongodb database the master uses. Depending how you setup the master, usually the mongodb is running on a container within the same node as the master API. There are lot of good articles how to take Mongo backups from a container.

> If master crash how quick we can bring this up from backup?

If you have recent enough backup, usually the restore process can be done within minutes as the database is not that big usually.

> Is master used for only deploy services?

Yes, but it does many other things as well. It also stores the logs and stats for example for all your services.

> what is the role of master with existing/running services in grid?

Master will monitor the state of services so that the desired services are up-and-running and master will also re-schedule services in case of node failures and other such events. So essentially having the master down will not bring down all your services, you just cannot push any new changes to the grid until the master is up again.



In case you didn't find it already, we have a public Slack channel which can be also used for questions and discussion about Kontena platform. https://slack.kontena.io/

**Comment by santhoshkumarhirekerur** [comment]
I was reading blog http://blog.kontena.io/managing-data-in-volumes/.  When I create "named volumes" as given in this blog Is that helps me in production? 

How to mount existing files on host folder to this volume? .

**Comment by jnummelin** [comment]
There's no functionality on Docker AFAIK that would allow you to use a named volume and still have some files/folders from host side visible in that volume.

For the volume part, I think some options are described in https://github.com/kontena/kontena/issues/2259
