### ISSUE TITLE
Volume removal is slow

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2346]
When user removes a volume from Kontena Master it might take couple of minutes when actual volumes are removed from the nodes. Master should send an event to nodes so that they can cleanup volumes faster -> less wait for user.

**Comment by SpComb** [comment]
Note that because of the async nature of the server-agent protocol, I suspect there's likely to still be some race conditions between service remove / volume remove, where either the volume remove could fail because the service is still in use, or the service remove could fail because the volume is still in use? Those races should just be temporary though, and the agent will eventually retry and fix it.

However, I suspect there could also be a potential race between service+volume remove -> immediately following volume+service create, if the new service gets created and picks up the existing volume before it is removed? The `VolumeManager#ensure_volume` used by both the `ServicePods::Creator` and `VolumeManager#populate_volumes_from_master`doesn't care about the volume ID, and it would happily accept the existing volume if it has not yet been removed. The `VolumeManager#populate_volumes_from_master` would then see the existing volume with the old volume ID, and attempt to remove it, which would then fail because it's still in use by the new service. Later, the `VolumeManager` might then actually succeed in removing it...

I don't know if that race condition is actually possible, it might require very unlikely timings and failures... but if it does, it will result in a persistent inconsistency that might eventually lead to data loss... ?
