### ISSUE TITLE
Kontena 1.3.1 ERROR : connection closed with code 4020: agent clock offset

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2474]
After upgrading Kontena server and agent from 1.2.2 . I am getting below error.  When I launch the agent, getting below error with latest version. Everything working fine with 1.2.2.

connection closed with code 4020: agent clock offset

What is time drift tolerance with Kontena server and agent?

**Comment by SpComb** [comment]
> After upgrading Kontena server and agent from 1.2.2 . I am getting below error

Yes, 1.3 includes #2144 with agent clock offset checks on connect. This is because the agent service container checks depend on master-host node clock synchronization:  #2298

> `connection closed with code 4020: agent clock offset`

The error message should continue, with something like `agent clock offset XXXs exceeds threshold`.

How large are your clock offsets? Are you using NTP for time synchronization on the master and host nodes?

> What is time drift tolerance with Kontena server and agent?

See the [Environment Variables](https://kontena.io/docs/references/environment-variables.html) reference:

> * KONTENA_CLOCK_SKEW: acceptable clock skew for connecting agents (default: 1.0s)
> 
>    The acceptable range of clock offsets is between WEBSOCKET_TIMEOUT + KONTENA_CLOCK_SKEW (default: 6.0) seconds in the past, and KONTENA_CLOCK_SKEW (default: 1.0) seconds in the future.


This should probably also be mentioned elsewhere in the docs... probably under the Host Nodes section.

**Comment by santhoshkumarhirekerur** [comment]
I just did NTP synchronization. Its working now.

https://www.digitalocean.com/community/tutorials/how-to-set-up-timezone-and-ntp-synchronization-on-ubuntu-14-04-quickstart

**Comment by SpComb** [comment]
Yes, using NTP for clock synchronization is important. The nodes provisioned via Kontena plugins use CoreOS with systemd-timesyncd.
