### ISSUE TITLE
Grid admin should be able to invite users to a grid

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2574]
Currently it requires that master_admin first invites user to master.

**Comment by SpComb** [comment]
So [`kontena master user invite`](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/master/user/invite_command.rb#L31) calls [`POST /oauth2/authorize` `{ email: email, response_type: 'invite' }`](https://github.com/kontena/kontena/blob/master/server/app/routes/oauth2/authorization_api.rb#L93), which runs [`Users::Invite`](https://github.com/kontena/kontena/blob/master/server/app/mutations/users/invite.rb#L14), which checks [`self.user.can_create?(User)`](https://github.com/kontena/kontena/blob/master/server/app/authorizers/user_authorizer.rb#L2), which is defined as `user.master_admin?`.

That should be changed to also accept a user with the `grid_admin` role? That will not depend on what grids they are assigned to, because users that are being created/invited are independent of any grids.


Usecase would be: a user is assigned to some grid X, and has the `grid_admin` role, but not the `master_admin` role. They can `kontena master user invite foo@cloud.kontena.io`, which creates a new user, and then `kontena grid users add foo@cloud.kontena.io`, so that the new user can `kontena master join ... <invite code>` and has access to the X grid?

The initial user with the `grid_admin` role will then be able to `kontena grid users add` -> [`Grids::AssignUser`](https://github.com/kontena/kontena/blob/master/server/app/mutations/grids/assign_user.rb#L10), because [`current_user.can_assign?(self.user, {to: self.grid})`](https://github.com/kontena/kontena/blob/master/server/app/authorizers/user_authorizer.rb#L12) accepts both `user.master_admin? || user.grid_admin?(grid)`. The initial user will however not be able to give the new user the `grid_admin` role, because [`Users::AddRole`](https://github.com/kontena/kontena/blob/master/server/app/mutations/users/add_role.rb#L20) is also reserved for [`master_admin?`](https://github.com/kontena/kontena/blob/master/server/app/authorizers/role_authorizer.rb#L7).

**Comment by SpComb** [comment]
Instead of changing the scope of the `grid_admin` role, I suggest a new role that grants some of the privileges associated with the `master_admin` role: the new `user_admin` role could allow inviting/removing users. Not sure about granting the `grid_admin` / `user_admin` roles, though?
