### ISSUE TITLE
[Question] Newcomer's questions about Kontena

### ISSUE THREAD

**Issue by hrstoyanov** [kontena/kontena#2620]
Hello,
I just learned about Kontena (very exciting) but could not find answers to my questions in the FAQ on the web site. Here are my questions:

1. Kontena is written in Ruby, where most other container frameworsk - in Go. Ruby is notoriously slow and under performing language. How does that impact Kontena?

2. [WireGuard](http://WireGuard.io) is a new and fast VPN solution that is built because OpenVPN is too slow and IPSec - too complicated. I see Kontena uses both OpenVPN and IPSec! Again, what is the performance impact, especially because how bad th performance of OpenVPN is?

3. I am getting the impression that somehow Kontena slips in MongoDB in my system? I would prefer to have nothing to do with MongoDB for any reason...

I really like Kontena, but would be hesitant to use it if it slower than K8S and/or Docker Swarm due to Ruby and OpenVPN. 

Thanks

P.S: Sorry, I just saw that there is a Kontena forum. However, it does not allow for social login, which is why decided to leave the question here.

**Comment by miskun** [comment]
Hi! Good questions!

1. Short story: It does not impact Kontena. Long Story: Yes. Kontena is written in Ruby. Not going to start comparing different programming languages here since each of them have their own pros/cons. However, the choice of programming language has very limited impact on performance. The reason is that K8S, Kontena, Swarm (=the orchestrator) is mostly dealing with state of the system, providing management APIs and interacting with underlying components (these underlying components are affecting performance, but they are more or less the same, no matter which container platform you choose). The only advantage you might get with super powerful state machine optimized programming language is the time from issuing command via CLI tool and actually seeing something happening in the platform. My guess is that we are talking about few ms difference in here.

2. Short Story: No impact. Long Story: Kontena overlay network is not based on OpenVPN. The overlay network technology is Weave with fast data path. It is super fast. Therefore, OpenVPN has nothing to do with performance of Kontena. Since Kontena network is overlay, it is isolated from outside. If you want to access the Kontena Platform, you can use OpenVPN (or any other technology you want). The OpenVPN access is built-in so people who don't want to tinker can use it.

3. Kontena Master (that is the brain of operations) is using a database to store the state of the system. This database is MongoDB. Unfortunately, (today) it is not possible to use any other technology in here... But if you don't like Mongo, you can get Kontena Master as hosted solution from Kontena via Kontena Cloud.

Summary: Kontena is not slow. It's blazing fast and easy to use! I'd recommend you to join our Slack channel at https://slack.kontena.io to talk with Kontena devs and other users. Please close this issue if you are satisfied with my answer :)

**Comment by hrstoyanov** [comment]
@miskun 
I am  happy with the well thought out answers! I am closing the issue, but please update the FAQ so newcomers like me do not hit you with similar questions again :-)
