### ISSUE TITLE
Node disconnect event is not send properly into EventStream

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#2991]
Disconnected node is updated on the background and current `@node` instance is having the old information when publishing event.

**Comment by SpComb** [comment]
This is because the [`NodeUnplugger#update_node!`](https://github.com/kontena/kontena/blob/3d608c58a0c0ce046e3a3f2065c39431b2fbc13f/server/app/services/agent/node_unplugger.rb#L27) uses `HostNode.where(...).find_and_modify(...)` to set the `connected` attr, so that won't show up in the mongoid model used for the `@node.publish_update_event`.

The [`NodePlugger`](https://github.com/kontena/kontena/blob/3d608c58a0c0ce046e3a3f2065c39431b2fbc13f/server/app/services/agent/node_plugger.rb#L25)  should also behave exactly the same way... do the node update events on connect also have the wrong `connected` state?

**Comment by nevalla** [comment]
Yes, based on implementation it should behave the same way. However in cloud dashboard I will see node coming online, so are there some node info events that might trigger update event after node is coming online?

**Comment by SpComb** [comment]
The `/nodes/update` RPC is probably also triggering an event via [`node.attributes_from_docker `-> `node.save`](https://github.com/kontena/kontena/blob/3d608c58a0c0ce046e3a3f2065c39431b2fbc13f/server/app/services/rpc/node_handler.rb#L34), and that will have the `connected` state.
