### ISSUE TITLE
Encrypted fields should use random iv

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#3183]
Currently all symmetrically encrypted fields use static iv. It would be better to switch to use random iv.

**Comment by SpComb** [comment]
The only known impact of this is that an attacker with read access to mongo can tell which vault secrets share the same value. If you have write access to the vault API for one grid, and read access to the mongodb database shared by all grids, then you could use that to brute-force an encrypted vault secret in a different grid by guessing vault secret plaintexts in a different grid until you see a matching ciphertext in mongodb. I wouldn't consider that a very practical scenario.

AFAIK other impacts of AES-256-CBC IV reuse require attacker-controlled plaintexts or ciphertexts, i.e. write access to mongodb, or write access to the Kontena vault API. I wouldn't consider that a relevant threat model, because an attacker in that position wouldn't really need to bother with any of those IV-related weaknesses...

* https://crypto.stackexchange.com/questions/3883/why-is-cbc-with-predictable-iv-considered-insecure-against-chosen-plaintext-atta
* https://crypto.stackexchange.com/questions/5094/is-aes-in-cbc-mode-secure-if-a-known-and-or-fixed-iv-is-used
* https://crypto.stackexchange.com/questions/1078/how-can-cipher-block-chaining-cbc-in-ssl-be-attacked

The lack of a MAC in the SymmetricEncryption storage schema is probably a more significant issue, because it exposes a padding oracle... however, I wouldn't consider that part of the vault threat model either.

* https://crypto.stackexchange.com/questions/1066/does-the-xml-encryption-flaw-affect-ssl-tls

All of these other issues are mostly related to decrypting untrusted inputs, whereas the Kontena server only eveer uses SymmetricEncryption to decode trusted values from MongoDB. The lack of a MAC does, however, cause the practical issue of corrupted ciphertexts/keys resulting in corrupted plaintext instead of decryption errors...
