### ISSUE TITLE
Underscore should not be allowed in service names

### ISSUE THREAD

**Issue by yuruki** [kontena/kontena#3256]
Underscore ('_') is not allowed in DNS host names and can cause trouble with certain runtimes (e.g. Java). Kontena should display a warning when validating stack files and perhaps even remove underscores or replace them with a dash ('-') when deploying services.

**Comment by SpComb** [comment]
Agreed that stack and service names should be validated for use as DNS name labels.

While `_` technically works, I can imagine that it would act as a footgun with certain runtimes... I reckon it would make sense to fix the validation to disallow anything except `[a-z0-9\-]`, because I can't immediately think of any technical reason to use `_` instead of `-` in the stack/service names.

I don't think replacing `_` -> `-` in the container hostnames is a good idea though, it would just be confusing if you're trying to reference those names.

**Comment by SpComb** [comment]
One compromise would be to have the CLI warn about the use of `_` in names, while still allowing those services on the server API... that way we wouldn't need to annoy anyone too much by breaking any existing services using underscores.
