### ISSUE TITLE
support for kontena.yml defined volumes

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#524]
Currently kontena epects all containers defined in kontena.yml to keep running, and restarts them when they stop.
This does not support for explicitly defined volumes in the kontena.yml.

As a workaround/hack, a continuously running script (eg using sleep) is needed.

A proper support for explicitly defined volumes is needed

**Comment by mtrofimm** [comment]
:+1:

**Comment by zbyte64** [comment]
Perhaps supporting volume drivers would help? If that was possible a user could use convoy or flocker to persist volumes across multiple hosts.

**Comment by jakolehm** [comment]
@zbyte64 kontena will definitely support volumes (and drivers) in the future. We just want to make sure that it's not going to complicate installation or maintenance.

**Comment by giovannicandido** [comment]
I was planning to use the volume driver convoy, to persist container data in a separated lvm disk, while docker images are on the main disk.
That disk will have proper backups to S3 storage, if everything crash I can rebuild the host from scratch and attach the new volumes.
Not the most reliable plan on the world, but the best for now.
I'm surprise that kontena doesn't have this native feature of docker. Also multiple networks are not supported. I was thinking that one could extend the docker-compose.yml with kontena specific features, therefore, full docker support.

That doesn't seem the case. Now I have seen in the documentation that kontena.yml is not a superset of docker-compose.yml, that must be because kontena is not just for docker.

I find the features of kontena, like vault and hooks, really awesome. I will drop this feedback here 👍

**Comment by jakolehm** [comment]
@giovannicandido you can use volume drivers with Kontena if you setup those volumes manually (outside from Kontena). Just define named volume in Kontena service that points to the volume created with Convoy. 

Example:
```
services:
  db:
    image: db:latest
    volumes:
      - my_convoy_volume:/data
```

**Comment by giovannicandido** [comment]
@jakolehm Thanks, that can fullfill my case.
